# -*- coding: utf-8 -*-
"""歡迎使用 Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# -*- coding: utf-8 -*-
"""weather_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yDq7OqYtp_50-pzdsgSEeDLnDeG8uV9y
"""



import requests
import streamlit as st
import pandas as pd

st.title("🌥台灣的氣象資料 Dashboard")

API_KEY = "CWA-5724EC9B-289C-4CBD-AD69-E4FF4934C108"
LOCATION = st.selectbox("選擇城市",["Yunlin","Taipei","Kaohsiung"])

url = f"https://opendata.cwa.gov.tw/api/v1/rest/datastore/F-C0032-001?Authorization={API_KEY}"
res = requests.get(url)
data = res.json()

location_data = data["records"]["location"][0]
st.subheader(f"{location_data["locationName"]}36小時預報")

for element in location_data["weatherElement"]:
    name = element["elementName"]
    value = element["time"][0]["parameter"]["parameterName"]
    st.write(f"{name}:{value}")