# -*- coding: utf-8 -*-
"""weather_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yDq7OqYtp_50-pzdsgSEeDLnDeG8uV9y
"""



import requests
import streamlit as st
import pandas as pd

st.title("🌥 台灣的氣象資料 Dashboard")

API_KEY = "CWA-C9E52E67-5C22-4074-A61B-C48E190762DE"
LOCATION = st.selectbox("選擇城市", ["雲林縣","台北市","高雄市","嘉義縣"])

url = f"https://opendata.cwa.gov.tw/api/v1/rest/datastore/F-C0032-001?Authorization={API_KEY}"
res = requests.get(url , verify=False)
data = res.json()

# 正確命名變數
locations = data["records"]["location"]
location_data = next((loc for loc in locations if loc["locationName"] == LOCATION), None)

if location_data is None:
    st.error(f"找不到 {LOCATION} 的資料")
    st.stop()

st.subheader(f"{location_data['locationName']} 36小時預報")

for element in location_data["weatherElement"]:
    name = element["elementName"]
    value = element["time"][0]["parameter"]["parameterName"]
    st.write(f"{name}: {value}")
